<div class="payment_estpay_container payment_method_lhv">
    <?php echo $this->getChildHtml('estpay_lhv_description') ?>
    <form id="GatewayForm" name="lhv" action="<?php echo $this->getGatewayUrl() ?>" method="POST" target="_top">
        <input type="image" src="<?php echo $this->getMethodLogoUrl(); ?>" onclick="this.form.submit()" class="payment-gateway-logo lhv_logo"/>
        <?php foreach ($this->getFields() as $key => $value) { ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
        <?php } ?>
    </form>
    <?php echo $this->getQuickRedirectScript(); ?>
</div>